default: &default
  # secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_key_base: "dfjueu9324hdsifHJFJkdfjdkfi394349dKIJFJIFJIFJIDFJI94w9034593450KKGJIDGJIIJEWORIJEITJIOERTERGIDIOJGIOET2309902390434IRIJERGIJ"
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
